[package]
name = "amri-android-ffi"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
amri-core = { path = "../amri-core" }
amri-secrets = { path = "../amri-secrets" }
getrandom.workspace = true
jni.workspace = true

[target.'cfg(target_os = "android")'.dependencies]
tokio = { version = "1", features = ["rt-multi-thread"] }
tun2proxy = { version = "0.8.3", default-features = false }
