// Generated by scripts/generate_ui_theme.py. Do not edit by hand.
package ru.amri.vpn

import android.graphics.Color

internal object GeneratedAmriTheme {
    val backgroundColor: Int = Color.rgb(3, 8, 18)
    val mutedTextColor: Int = Color.rgb(150, 150, 150)
    val detailTextColor: Int = Color.rgb(165, 173, 190)
    val actionTextColor: Int = Color.rgb(205, 225, 245)
    val cardColor: Int = Color.rgb(22, 27, 36)
    val accentColor: Int = Color.rgb(67, 104, 255)
    val inactiveControlColor: Int = Color.rgb(34, 40, 52)

    const val screenPaddingHorizontal = 22
    const val screenPaddingTop = 22
    const val screenPaddingBottom = 28
    const val iconButtonSize = 46
    const val powerButtonSize = 124
    const val cardPadding = 22
    const val cardRadius = 18
    const val modeCornerRadius = 16
    const val sectionGap = 18
}
