// Generated by scripts/generate_ui_theme.py. Do not edit by hand.
pub const PANEL: Color32 = Color32::from_rgb(13, 16, 22);
pub const WINDOW: Color32 = Color32::from_rgb(19, 23, 31);
pub const BACKDROP: Color32 = Color32::from_rgb(3, 8, 18);
pub const SURFACE_MUTED: Color32 = Color32::from_rgb(24, 29, 39);
pub const SURFACE: Color32 = Color32::from_rgb(22, 27, 36);
pub const HERO_SURFACE: Color32 = Color32::from_rgb(24, 31, 44);
pub const ACCENT: Color32 = Color32::from_rgb(67, 104, 255);
pub const TEXT_MUTED: Color32 = Color32::from_rgb(150, 150, 150);
pub const CARD_RADIUS: u8 = 18;
pub const HERO_RADIUS: u8 = 24;
pub const CONTROL_RADIUS: u8 = 12;
pub const CARD_MARGIN: i8 = 22;
pub const HERO_MARGIN: i8 = 24;
pub const ITEM_SPACING_X: f32 = 12.0;
pub const ITEM_SPACING_Y: f32 = 12.0;
pub const BUTTON_PADDING_X: f32 = 16.0;
pub const BUTTON_PADDING_Y: f32 = 10.0;
