#!/usr/bin/env python3
"""Validate the approved AMRI PNG used by the Windows executable resource build.

The application icon itself is generated by apps/windows/build.rs, which can decode indexed PNGs
and safely scale oversized artwork for the Windows PE icon resource. NSIS shortcuts use that
embedded executable icon, so this helper intentionally does not create a second visual copy.
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "assets" / "brand" / "amri-icon.png"
PNG_SIGNATURE = b"\x89PNG\r\n\x1a\n"


def main() -> int:
    png = SOURCE.read_bytes()
    if not png.startswith(PNG_SIGNATURE) or len(png) < 24 or png[12:16] != b"IHDR":
        raise SystemExit("canonical AMRI icon is not a valid PNG")
    print(f"validated approved Windows icon source: {SOURCE.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
