#!/usr/bin/env python3
"""Generate platform theme constants from design/amri-ui-theme.json."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "design" / "amri-ui-theme.json"
RUST_OUTPUT = ROOT / "apps" / "windows" / "src" / "theme_generated.rs"
ANDROID_OUTPUT = (
    ROOT / "apps" / "android" / "app" / "src" / "main" / "java" / "ru" / "amri" / "vpn"
    / "GeneratedAmriTheme.kt"
)

HEX_COLOR = re.compile(r"^#[0-9A-Fa-f]{6}$")


def load_theme() -> dict:
    theme = json.loads(SOURCE.read_text(encoding="utf-8"))
    if theme.get("schema_version") != 1:
        raise ValueError("unsupported theme schema_version")
    for name, value in theme["colors"].items():
        if not isinstance(value, str) or not HEX_COLOR.fullmatch(value):
            raise ValueError(f"colors.{name} must be #RRGGBB")
    for group in ("shape", "spacing", "controls"):
        for name, value in theme[group].items():
            if not isinstance(value, int) or not 0 <= value <= 256:
                raise ValueError(f"{group}.{name} must be an integer from 0 to 256")
    return theme


def rgb(hex_value: str) -> tuple[int, int, int]:
    return tuple(int(hex_value[index:index + 2], 16) for index in (1, 3, 5))


def rust(theme: dict) -> str:
    colors = theme["colors"]
    shape = theme["shape"]
    spacing = theme["spacing"]
    controls = theme["controls"]
    names = {
        "panel": "PANEL", "window": "WINDOW", "background": "BACKDROP",
        "surface_muted": "SURFACE_MUTED", "surface": "SURFACE",
        "hero_surface": "HERO_SURFACE", "accent": "ACCENT", "text_muted": "TEXT_MUTED",
    }
    lines = ["// Generated by scripts/generate_ui_theme.py. Do not edit by hand."]
    for source, target in names.items():
        r, g, b = rgb(colors[source])
        lines.append(f"pub const {target}: Color32 = Color32::from_rgb({r}, {g}, {b});")
    lines.extend([
        f"pub const CARD_RADIUS: u8 = {shape['card_radius']};",
        f"pub const HERO_RADIUS: u8 = {shape['hero_radius']};",
        f"pub const CONTROL_RADIUS: u8 = {shape['control_radius']};",
        f"pub const CARD_MARGIN: i8 = {spacing['card_padding']};",
        f"pub const HERO_MARGIN: i8 = {spacing['hero_padding']};",
        f"pub const ITEM_SPACING_X: f32 = {spacing['item_x']}.0;",
        f"pub const ITEM_SPACING_Y: f32 = {spacing['item_y']}.0;",
        f"pub const BUTTON_PADDING_X: f32 = {spacing['button_x']}.0;",
        f"pub const BUTTON_PADDING_Y: f32 = {spacing['button_y']}.0;",
        "",
    ])
    return "\n".join(lines)


def android(theme: dict) -> str:
    colors = theme["colors"]
    shape = theme["shape"]
    spacing = theme["spacing"]
    controls = theme["controls"]
    def color(name: str) -> str:
        r, g, b = rgb(colors[name])
        return f"Color.rgb({r}, {g}, {b})"
    return f'''// Generated by scripts/generate_ui_theme.py. Do not edit by hand.
package ru.amri.vpn

import android.graphics.Color

internal object GeneratedAmriTheme {{
    val backgroundColor: Int = {color('background')}
    val mutedTextColor: Int = {color('text_muted')}
    val detailTextColor: Int = {color('detail_text')}
    val actionTextColor: Int = {color('action_text')}
    val cardColor: Int = {color('surface')}
    val accentColor: Int = {color('accent')}
    val inactiveControlColor: Int = {color('inactive_control')}

    const val screenPaddingHorizontal = {spacing['screen_horizontal']}
    const val screenPaddingTop = {spacing['screen_top']}
    const val screenPaddingBottom = {spacing['screen_bottom']}
    const val iconButtonSize = {controls['icon_button']}
    const val powerButtonSize = {controls['power_button']}
    const val cardPadding = {spacing['card_padding']}
    const val cardRadius = {shape['card_radius']}
    const val modeCornerRadius = {shape['mode_radius']}
    const val sectionGap = {spacing['section_gap']}
}}
'''


def write_or_check(path: Path, content: str, check: bool) -> bool:
    current = path.read_text(encoding="utf-8") if path.exists() else None
    if current == content:
        return True
    if check:
        print(f"generated file is stale: {path.relative_to(ROOT)}", file=sys.stderr)
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        theme = load_theme()
        ok = write_or_check(RUST_OUTPUT, rust(theme), args.check)
        ok = write_or_check(ANDROID_OUTPUT, android(theme), args.check) and ok
        return 0 if ok else 1
    except (KeyError, ValueError, json.JSONDecodeError) as error:
        print(f"invalid AMRI UI theme: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
